# Assignment 2 - Numpy Array Operations
1. Pick 5 interesting Numpy array functions
2. Give explanation and 3 examples for each function

### Numpy
> Numpy is a library package used in Python programming to operate various high level mathematical equations on arrays

* np.mean()
* np.std()
* np.split()
* np.vstack or np.hstack()
* np.percentile()



In [3]:
import numpy as np
# List of functions explained 
function1 = np.mean  # Takes the mean value of an numpy array
function2 = np.std # Takes the standard deviation of an numpy array
function3 = np.split # Splits an array
function4 = np.vstack or np.hstack # Takes the median value of an numpy array
function5 = np.percentile # takes a number and returns the percent of it of the sum of an numpy array

In [4]:
np_arr = np.linspace(4.52462377, 10.56812481, 36)
np_arr = np_arr.reshape((4,3,3))
np_arr

array([[[ 4.52462377,  4.69729523,  4.86996669],
        [ 5.04263814,  5.2153096 ,  5.38798106],
        [ 5.56065252,  5.73332398,  5.90599544]],

       [[ 6.07866689,  6.25133835,  6.42400981],
        [ 6.59668127,  6.76935273,  6.94202419],
        [ 7.11469564,  7.2873671 ,  7.46003856]],

       [[ 7.63271002,  7.80538148,  7.97805294],
        [ 8.15072439,  8.32339585,  8.49606731],
        [ 8.66873877,  8.84141023,  9.01408169]],

       [[ 9.18675314,  9.3594246 ,  9.53209606],
        [ 9.70476752,  9.87743898, 10.05011044],
        [10.22278189, 10.39545335, 10.56812481]]])

In [5]:
np_arr2 = np.linspace(2.4687456788, 34.156412377, 27)
np_arr2 = np_arr2.reshape((3,3,3))
np_arr2

array([[[ 2.46874568,  3.68750209,  4.9062585 ],
        [ 6.12501491,  7.34377132,  8.56252774],
        [ 9.78128415, 11.00004056, 12.21879697]],

       [[13.43755338, 14.65630979, 15.8750662 ],
        [17.09382262, 18.31257903, 19.53133544],
        [20.75009185, 21.96884826, 23.18760467]],

       [[24.40636109, 25.6251175 , 26.84387391],
        [28.06263032, 29.28138673, 30.50014314],
        [31.71889955, 32.93765597, 34.15641238]]])

### Example 1 - np.mean()

In [6]:
# This function basically just takes the mean value of an array
# regardless its dimensions
print(f"Total Mean: {np.mean(np_arr)}")

# You can also get the mean value of a specific element
# By using slicing or indexing
print(f"Mean of sliced: {np.mean(np_arr[1:, 0:2, 0:2])}")

# You can also get the mean of two different parts of the array
print(f"Mean of joined specific element vectors: {np.mean(np.vstack((np_arr[3, 0:2], np_arr2[0, 2])))}")

Total Mean: 7.546374290000001
Mean of sliced: 7.9780529357142855
Mean of joined specific element vectors: 10.078968045980588


### Example 2 - np.std()

In [38]:
# Example 2, Standard Deviation
# Similar to mean, you can get the standard deviation of a whole array
print(f"STD of arr1: {np.std(np_arr)}")

# You can also get the std of two arrays
print(f"STD of arr1 and arr2: {np.std(np_arr[0:3] + np_arr2)}") # Sliced arr 1 because (4,3,3)

# You can also get the STD of sliced arrays
print(f"STD of Sliced {np.std(np_arr[3, 0:2] + np_arr2[0:, 0:2, 0:])}")

STD of arr1: 1.7937619940583245
STD of arr1 and arr2: 10.83766604709401
STD of Sliced 9.265889247340958


### Example 3 - np.split()

In [78]:
# This function splits an array
# Split an array into 4
new_arr = np.arange(26)

# Splitting a 1D Array into two
sub1, sub2 = np.split(new_arr, 2)
print(f"1. Subarray = {sub1}")
print(f"2. Subarray = {sub2}")

arr1_top, arr1_bottom = np.split(np_arr, 2)

# adding np_arr's bottom to np_arr2's bottom
mixed = np.concatenate((np_arr2, arr1_bottom[0:1]), axis=0)

# Now adding mixed's top to the bottom of np_arr
top, bottom = np.split(mixed, 2)

mixed2 = np.concatenate((np_arr, top), axis = 0)

# Splitting mixed into 3 parts
top1, mid, bottom1 = np.split(mixed2, 3)

print(f"\ntop: {top1}")
print(f"\nmid: {mid}")
print(f"\nbottom: {bottom1}")


1. Subarray = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
2. Subarray = [13 14 15 16 17 18 19 20 21 22 23 24 25]

top: [[[4.52462377 4.69729523 4.86996669]
  [5.04263814 5.2153096  5.38798106]
  [5.56065252 5.73332398 5.90599544]]

 [[6.07866689 6.25133835 6.42400981]
  [6.59668127 6.76935273 6.94202419]
  [7.11469564 7.2873671  7.46003856]]]

mid: [[[ 7.63271002  7.80538148  7.97805294]
  [ 8.15072439  8.32339585  8.49606731]
  [ 8.66873877  8.84141023  9.01408169]]

 [[ 9.18675314  9.3594246   9.53209606]
  [ 9.70476752  9.87743898 10.05011044]
  [10.22278189 10.39545335 10.56812481]]]

bottom: [[[ 2.46874568  3.68750209  4.9062585 ]
  [ 6.12501491  7.34377132  8.56252774]
  [ 9.78128415 11.00004056 12.21879697]]

 [[13.43755338 14.65630979 15.8750662 ]
  [17.09382262 18.31257903 19.53133544]
  [20.75009185 21.96884826 23.18760467]]]


### Example 4 - np.vstack() and np.hstack()

In [105]:
# What np.vstack does is basically contatenates an array vertically, while np.hstack() concatenates an array horizontally
mixed_arr = np.vstack((np_arr, np_arr2))
mixed_arr2 = np.hstack((np_arr[0:3], np_arr2))


In [106]:

# Notice the output has basically just stacked np_arr2 just below it
print(f"{mixed_arr} End")


[[[ 4.52462377  4.69729523  4.86996669]
  [ 5.04263814  5.2153096   5.38798106]
  [ 5.56065252  5.73332398  5.90599544]]

 [[ 6.07866689  6.25133835  6.42400981]
  [ 6.59668127  6.76935273  6.94202419]
  [ 7.11469564  7.2873671   7.46003856]]

 [[ 7.63271002  7.80538148  7.97805294]
  [ 8.15072439  8.32339585  8.49606731]
  [ 8.66873877  8.84141023  9.01408169]]

 [[ 9.18675314  9.3594246   9.53209606]
  [ 9.70476752  9.87743898 10.05011044]
  [10.22278189 10.39545335 10.56812481]]

 [[ 2.46874568  3.68750209  4.9062585 ]
  [ 6.12501491  7.34377132  8.56252774]
  [ 9.78128415 11.00004056 12.21879697]]

 [[13.43755338 14.65630979 15.8750662 ]
  [17.09382262 18.31257903 19.53133544]
  [20.75009185 21.96884826 23.18760467]]

 [[24.40636109 25.6251175  26.84387391]
  [28.06263032 29.28138673 30.50014314]
  [31.71889955 32.93765597 34.15641238]]] End


In [107]:
# Notice how the 1D part is the same but the 2D part has more elements
print(f"{mixed_arr2} End")

[[[ 4.52462377  4.69729523  4.86996669]
  [ 5.04263814  5.2153096   5.38798106]
  [ 5.56065252  5.73332398  5.90599544]
  [ 2.46874568  3.68750209  4.9062585 ]
  [ 6.12501491  7.34377132  8.56252774]
  [ 9.78128415 11.00004056 12.21879697]]

 [[ 6.07866689  6.25133835  6.42400981]
  [ 6.59668127  6.76935273  6.94202419]
  [ 7.11469564  7.2873671   7.46003856]
  [13.43755338 14.65630979 15.8750662 ]
  [17.09382262 18.31257903 19.53133544]
  [20.75009185 21.96884826 23.18760467]]

 [[ 7.63271002  7.80538148  7.97805294]
  [ 8.15072439  8.32339585  8.49606731]
  [ 8.66873877  8.84141023  9.01408169]
  [24.40636109 25.6251175  26.84387391]
  [28.06263032 29.28138673 30.50014314]
  [31.71889955 32.93765597 34.15641238]]] End


### Example 5 - np.percentile()

In [141]:
# np.percentile takes two arguments, first is the array, and second is a number percentage that you are looking for the value
print(f"25 percent of the sum of np_arr : {np.percentile(np_arr, 25)}") 

# You can also use slicing to get the percentage of that only specific elements
print(f"48 percent of the sum of np_arr[0, 0:2] : {np.percentile(np_arr2[0, 0:2] , 48)}") 

# You can also get the percentage of the product of two vectors
print(f"78 percent of the product of np_arr[0,0] and np_arr2 : {np.percentile((np_arr[0, 0] * np_arr2) , 78)}") 

25 percent of the sum of np_arr : 6.03549903
48 percent of the sum of np_arr[0, 0:2] : 5.393761066326154
78 percent of the product of np_arr[0,0] and np_arr2 : 128.02450388696778
