In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5


In [3]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87,134, 58]
sinnoh = [102,43,37]
unova = [69, 96, 70]
w = [w1, w2, w3]

In [4]:
def crop_yield(region, w):
    result = 0
    for x, w in zip(region, w):
        result += x * w
    return result

In [5]:
regions = [kanto, johto, hoenn, sinnoh, unova]
names = ["kanto", "johto", "hoenn", "sinnoh", "unova"]
for region, name in zip(regions, names):
    print(f"Crop Yield in {name.title()} : {crop_yield(region,w):.2f}")
    

Crop Yield in Kanto : 56.80
Crop Yield in Johto : 76.90
Crop Yield in Hoenn : 81.90
Crop Yield in Sinnoh : 57.70
Crop Yield in Unova : 74.90


In [6]:
import numpy as np
kanto = np.array([73, 67, 43])
johto = np.array([91, 88, 64])
hoenn = np.array([87,134, 58])
sinnoh = np.array([102,43,37])
unova = np.array([69, 96, 70])
w = np.array([w1, w2, w3])
regions = [kanto, johto, hoenn, sinnoh, unova]

regions

[array([73, 67, 43]),
 array([91, 88, 64]),
 array([ 87, 134,  58]),
 array([102,  43,  37]),
 array([69, 96, 70])]

In [7]:
for region in regions:
    print(f"{type(region)}")

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
# product of the two vectors using np.dot method
np.dot(kanto, w)

56.8

In [9]:
# np.dot alternative, .sum
(kanto * w).sum()

56.8

In [10]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
""" Always specify data type for precise output """
# dtype=np.int64
arr1_np = np.array(arr1, dtype=np.int64)
arr2_np = np.array(arr2, dtype=np.int64)

In [11]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 500 ms
Wall time: 614 ms


833332333333500000

In [12]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 1 ms


833332333333500000

In [13]:
%%time
(arr1_np * arr2_np).sum()

CPU times: total: 15.6 ms
Wall time: 9.99 ms


833332333333500000

Notice the CPU and wall time difference

In [14]:
climate_data = np.array(regions, dtype=np.int64)
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]], dtype=int64)

In [15]:
climate_data.shape

(5, 3)

In [16]:
w

array([0.3, 0.2, 0.5])

In [17]:
w.shape

(3,)

In [18]:
# 3D array
arr3 = np.array(
    [
    [[11,12,16],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.5]]]
                )

In [19]:
arr3.shape

(2, 2, 3)

In [20]:
w.dtype

dtype('float64')

In [21]:
climate_data.dtype

dtype('int64')

In [22]:
%%time
np.matmul(climate_data, w)

CPU times: total: 0 ns
Wall time: 1 ms


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [23]:
%%time
climate_data @ w

CPU times: total: 0 ns
Wall time: 0 ns


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [24]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

climate_results = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_results

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [25]:
climate_results.shape

(10000, 3)

In [26]:
climate_results.dtype

dtype('float64')

In [27]:
%%time
yields = climate_results @ w
yields

CPU times: total: 0 ns
Wall time: 998 µs


array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [28]:
yields.shape

(10000,)

In [28]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]], dtype=int64)

In [29]:
climate_results

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [30]:
 # add climate_data to the end of climate result, add row
climate_results = np.concatenate((climate_results, climate_data), axis=0)
climate_results

array([[ 25.,  76.,  99.],
       [ 39.,  65.,  70.],
       [ 59.,  45.,  77.],
       ...,
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]])

In [31]:
yields = climate_results @ w
yields

array([72.2, 59.7, 65.2, ..., 81.9, 57.7, 74.9])

In [32]:
climate_total_results = np.concatenate((climate_results, yields.reshape(len(yields), 1)), axis=1)
climate_total_results

array([[ 25. ,  76. ,  99. ,  72.2],
       [ 39. ,  65. ,  70. ,  59.7],
       [ 59. ,  45. ,  77. ,  65.2],
       ...,
       [ 87. , 134. ,  58. ,  81.9],
       [102. ,  43. ,  37. ,  57.7],
       [ 69. ,  96. ,  70. ,  74.9]])

In [33]:
yields.reshape(len(yields))
yields

array([72.2, 59.7, 65.2, ..., 81.9, 57.7, 74.9])

In [34]:
#save
np.savetxt('climate.txt',
            climate_total_results,
            fmt='%.2f',
            delimiter=',',
            header='temperature, rainfall, humidity, yield_apples',
            comments='')

In [35]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [36]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [37]:
%%time
arr2 + arr3

CPU times: total: 0 ns
Wall time: 0 ns


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [38]:
# scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [39]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [40]:
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [41]:
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [42]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [43]:
arr2.shape

(3, 4)

In [44]:
arr4 = np.array([4, 5, 6, 7])
arr4.shape

(4,)

In [45]:
arr4 + arr2

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [46]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [47]:
arr5 = np.array([7,8])
arr5.shape

(2,)

In [48]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [49]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [50]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [51]:
(arr1 == arr2).sum() # takes all bool values and adds it

3

In [114]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]
    ])
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [53]:
# Single element
arr3[1, 1, 2]

36.0

In [130]:
arr3[0:, 0:2, :4]

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [74]:
arr3[1:, 1, 3]

array([18., 43.])

In [99]:
ones = np.zeros((3,2))

In [100]:
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [105]:
arr1_np * arr2_np

array([            0,       1000001,       2000004, ..., 1999991000009,
       1999994000004, 1999997000001], dtype=int64)

In [112]:
np.full([2, 3, 4], 32)

array([[[32, 32, 32, 32],
        [32, 32, 32, 32],
        [32, 32, 32, 32]],

       [[32, 32, 32, 32],
        [32, 32, 32, 32],
        [32, 32, 32, 32]]])